// GENERATED CODE - This file is generated by build_runner
// Run: flutter pub run build_runner build --delete-conflicting-outputs
part of 'router.dart';

// This is a temporary generated file. Run build_runner to regenerate properly.
typedef RouterRef = AutoDisposeProviderRef<GoRouter>;

final routerProvider = AutoDisposeProvider<GoRouter>((ref) {
  return router(ref as RouterRef);
});
